# Generated by Django 4.2.4 on 2024-09-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0007_add_salarys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=10, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Suite", "Suite"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Occupied", "Occupied"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
