# Generated by Django 4.2.4 on 2024-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0008_room"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.RemoveField(
            model_name="add_room",
            name="Room_Facility",
        ),
        migrations.RemoveField(
            model_name="add_room",
            name="Room_Floor",
        ),
        migrations.AddField(
            model_name="add_room",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Occupied", "Occupied"),
                    ("Maintenance", "Maintenance"),
                ],
                default="Available",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="add_room",
            name="Room_Number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="add_room",
            name="Room_Price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="add_room",
            name="Room_Type",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Double", "Double"),
                    ("Suite", "Suite"),
                ],
                max_length=10,
            ),
        ),
    ]
