# Generated by Django 4.2.4 on 2024-09-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0014_remove_authorregis_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Authorregis",
        ),
    ]
