# Generated by Django 4.2.4 on 2024-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0015_delete_authorregis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_booking",
            name="Check_in",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="online_booking",
            name="Check_out",
            field=models.DateField(),
        ),
    ]
