# Generated by Django 4.2.4 on 2024-09-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0017_remove_online_booking_nid_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="online_booking",
            name="Address",
        ),
    ]
