# Generated by Django 4.2.4 on 2024-09-08 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0023_restaurantorder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
