# Generated by Django 4.2.4 on 2024-09-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0024_invoice_updated_at_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="mpesa_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mpesa_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paypal_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paypal_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
