# Generated by Django 4.2.4 on 2024-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0026_online_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="room_charge",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
